/** Anchor ids for Inhaltsverzeichnis (must match section id attributes). */
export const DATENSCHUTZ_TOC = [
  { id: "einleitung-und-ueberblick", label: "Einleitung und Überblick" },
  { id: "anwendungsbereich", label: "Anwendungsbereich" },
  { id: "rechtsgrundlagen", label: "Rechtsgrundlagen" },
  { id: "kontaktdaten-des-verantwortlichen", label: "Kontaktdaten des Verantwortlichen" },
  { id: "speicherdauer", label: "Speicherdauer" },
  { id: "rechte-laut-datenschutz-grundverordnung", label: "Rechte laut Datenschutz-Grundverordnung" },
  { id: "datenuebertragung-in-drittlaender", label: "Datenübertragung in Drittländer" },
  { id: "sicherheit-der-datenverarbeitung", label: "Sicherheit der Datenverarbeitung" },
  { id: "kommunikation", label: "Kommunikation" },
  { id: "auftragsverarbeitungsvertrag-avv", label: "Auftragsverarbeitungsvertrag (AVV)" },
  { id: "cookies", label: "Cookies" },
  { id: "webhosting-einleitung", label: "Webhosting Einleitung" },
  { id: "website-baukastensysteme-einleitung", label: "Website Baukastensysteme Einleitung" },
  { id: "cookie-consent-management-platform-einleitung", label: "Cookie Consent Management Platform Einleitung" },
  { id: "security-anti-spam", label: "Security & Anti-Spam" },
  { id: "externe-onlineplattformen-einleitung", label: "Externe Onlineplattformen Einleitung" },
  { id: "webdesign-einleitung", label: "Webdesign Einleitung" },
  { id: "google-fonts-datenschutzerklaerung", label: "Google Fonts Datenschutzerklärung" },
  { id: "online-buchungssysteme-einleitung", label: "Online-Buchungssysteme Einleitung" },
  { id: "erklaerung-verwendeter-begriffe", label: "Erklärung verwendeter Begriffe" },
  { id: "schlusswort", label: "Schlusswort" },
] as const;
